
import java.sql.Date;
import java.time.LocalDate;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lmoentje
 */
public class ClerkInvoiceShow extends javax.swing.JFrame {

    //SHOW THE INVOICE DIE GEKOZEN IS BIJ ClerkInvoiceGiveNumber
    //--> DE STATIC RENTAL REQUEST DIE GEMAAKT IS IN DIE GUI
    //ClerkInvoiceGiveNumber.getRentalInvoice()
    
    /**
     * Creates new form ShowInvoice
     */
    public ClerkInvoiceShow() {
        initComponents();
        String supplier=ClerkInvoiceGiveNumber.getRentalInvoice().getSelectedSupplier();
        supplierName.setText(supplier);
        String eqCodes = ClerkInvoiceGiveNumber.getRentalInvoice().getSelectedEquipment();
        Equipmentcodes.setText(eqCodes);
        String start = ClerkInvoiceGiveNumber.getRentalInvoice().getRentalPeriodStart().toString();
        startPeriod.setText(start);
        String end = ClerkInvoiceGiveNumber.getRentalInvoice().getRentalPeriodEnd().toString();
        endPeriod.setText(end);
        String p = ClerkInvoiceGiveNumber.getRentalInvoice().getDailyRentalPrice();
        String totPrijs = Double.toString(ClerkPOMake.getTotalePrijs());
        price.setText(totPrijs);
       String nummer = Integer.toString(ClerkInvoiceGiveNumber.getRentalInvoice().getRequestNumber());
       invoiceNR.setText(nummer);
        datumVandaag.setText(LocalDate.now().toString());
        String nummerI = Integer.toString(ClerkInvoiceGiveNumber.getRentalInvoice().getRequestNumber());
        purchaseOrder.setText(nummerI);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        SupplierOK = new javax.swing.JButton();
        invoiceNR = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        datumVandaag = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        supplierName = new javax.swing.JLabel();
        purchaseOrder = new javax.swing.JLabel();
        Equipmentcodes = new javax.swing.JLabel();
        startPeriod = new javax.swing.JLabel();
        endPeriod = new javax.swing.JLabel();
        price = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Invoice");

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        SupplierOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SupplierOK.setText("Invoice supplier is OK!");
        SupplierOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierOKActionPerformed(evt);
            }
        });

        invoiceNR.setText("number");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nr:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Date:");

        datumVandaag.setText("date");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Supplier:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Purchase order:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Equipment code(s):");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Start of rental period:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("End of rental period:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Price:");

        supplierName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        supplierName.setText("supplier");

        purchaseOrder.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        purchaseOrder.setText("PO");

        Equipmentcodes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Equipmentcodes.setText("EqCodes");

        startPeriod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        startPeriod.setText("Start period");

        endPeriod.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        endPeriod.setText("End period");

        price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        price.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                                .addComponent(SupplierOK))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(datumVandaag)
                                    .addComponent(invoiceNR))))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(supplierName)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(purchaseOrder)
                                    .addComponent(Equipmentcodes)
                                    .addComponent(startPeriod)
                                    .addComponent(endPeriod)
                                    .addComponent(price))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(invoiceNR)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(datumVandaag))))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(supplierName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(purchaseOrder))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Equipmentcodes))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(startPeriod))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(endPeriod))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(price))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(SupplierOK))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.dispose();
        StartschermSiteEngineer.getStartSiteEngineer().setVisible(true);
        
    }//GEN-LAST:event_cancelActionPerformed

    private void SupplierOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierOKActionPerformed
        this.dispose();
        ClerkInvoiceGiveNumber.getRentalInvoice().setCurrentStatus(RentalStatus.submittedForPayment);
        JOptionPane.showMessageDialog(null, "Please contact the financial department to pay the invoice.");
        Startscherm.getB().setVisible(true);
        
        try {
            RentalRequest.saveRR(ClerkInvoiceGiveNumber.getRentalInvoice());
            //Event e = new Event(ClerkInvoiceGiveNumber.getRentalInvoice().getRequestNumber(), ClerkInvoiceGiveNumber.getRentalInvoice().getCurrentStatus(), ClerkInvoiceGiveNumber.getRentalInvoice().getEmployeeID(), "INVOICE OK ");
            // Event.saveEvent(e);
                       
        } catch (DBException ex) {
            System.out.println("Error in ClerkInvoiceShow");
            Startscherm.getB().setVisible(true);
        }
        int i = 1;
        int a = 2;
        Date dat = Date.valueOf(LocalDate.now());
        String supplier = "NAAM";
        String purchaseOrder = "NAAM";
        int eqCo = 1;
        Date rentalEnd = Date.valueOf(LocalDate.now());
        Date rentalStart = Date.valueOf(LocalDate.now());
        double price = 0.00;
        String nameSupplier = "NAAM";
        
        Invoice inv = new Invoice(i, a, dat, supplier, purchaseOrder, eqCo, rentalStart, rentalEnd, price, nameSupplier);
        try {
            Invoice.saveI(inv);
        } catch (DBException ex) {
            System.out.println("Error in ClerkInvoice.");
            Startscherm.getB().setVisible(true);
        }
        
        
    }//GEN-LAST:event_SupplierOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClerkInvoiceShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClerkInvoiceShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClerkInvoiceShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClerkInvoiceShow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClerkInvoiceShow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Equipmentcodes;
    private javax.swing.JButton SupplierOK;
    private javax.swing.JButton cancel;
    private javax.swing.JLabel datumVandaag;
    private javax.swing.JLabel endPeriod;
    private javax.swing.JLabel invoiceNR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel price;
    private javax.swing.JLabel purchaseOrder;
    private javax.swing.JLabel startPeriod;
    private javax.swing.JLabel supplierName;
    // End of variables declaration//GEN-END:variables
}
