
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lmoentje
 */
public class Startscherm extends javax.swing.JFrame {

    /**
     * Creates new form Startscherm
     */
    public Startscherm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tekstbuildit = new javax.swing.JLabel();
        tekstchoosetask = new javax.swing.JLabel();
        makeReRe = new javax.swing.JButton();
        adjustReRe = new javax.swing.JButton();
        makePO = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        tekstbuildit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tekstbuildit.setForeground(new java.awt.Color(51, 51, 255));
        tekstbuildit.setText("BuildIt");

        tekstchoosetask.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        tekstchoosetask.setText("Choose your task");

        makeReRe.setText("Make rental request");
        makeReRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makeReReMouseClicked(evt);
            }
        });
        makeReRe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeReReActionPerformed(evt);
            }
        });

        adjustReRe.setText("Adjust rental request");
        adjustReRe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adjustReReMouseClicked(evt);
            }
        });

        makePO.setText("Make Purchase Order");
        makePO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                makePOMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tekstchoosetask)
                    .addComponent(tekstbuildit)
                    .addComponent(makeReRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adjustReRe, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(makePO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tekstbuildit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tekstchoosetask)
                .addGap(18, 18, 18)
                .addComponent(makeReRe)
                .addGap(18, 18, 18)
                .addComponent(adjustReRe)
                .addGap(18, 18, 18)
                .addComponent(makePO)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void makeReReActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeReReActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makeReReActionPerformed

    private void makeReReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makeReReMouseClicked
        // TODO add your h
        this.setVisible(false);
        RentalRequestForm njf;
               try {
                   njf = new RentalRequestForm(); 
                   njf.setVisible(true);
               } catch (DBException ex) {
                   Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
               }
               
    }//GEN-LAST:event_makeReReMouseClicked

    private void makePOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_makePOMouseClicked
        this.setVisible(false);
        MakePurchaseOrder PO;
               //try {
                   PO = new MakePurchaseOrder(); 
                   PO.setVisible(true);
               //} 
               /*catch (DBException ex) {
                   Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
               }
               */
               
    }//GEN-LAST:event_makePOMouseClicked

    private void adjustReReMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adjustReReMouseClicked
        this.setVisible(false);
        GiveNumberToAdjustReRe adj;
               //try {
                   adj = new GiveNumberToAdjustReRe(); 
                   adj.setVisible(true);
               //} 
               /*catch (DBException ex) {
                   Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
               }
               */
    }//GEN-LAST:event_adjustReReMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startscherm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adjustReRe;
    private javax.swing.JButton makePO;
    private javax.swing.JButton makeReRe;
    private javax.swing.JLabel tekstbuildit;
    private javax.swing.JLabel tekstchoosetask;
    // End of variables declaration//GEN-END:variables
}
