
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author lmoentje
 */
public class Startscherm extends javax.swing.JFrame {

    /**
     * Creates new form Startscherm
     */
    public Startscherm() {
        initComponents();
    }
    public static Startscherm b = new Startscherm();

    public static Startscherm getB() {
        return b;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tekstbuildit = new javax.swing.JLabel();
        siteEngineer = new javax.swing.JButton();
        clerk = new javax.swing.JButton();
        worksEngineer = new javax.swing.JButton();
        showAll = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(java.awt.Color.pink);

        tekstbuildit.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tekstbuildit.setForeground(new java.awt.Color(51, 51, 255));
        tekstbuildit.setText("BuildIT");

        siteEngineer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siteEngineer.setText("I'm a site engineer");
        siteEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siteEngineerActionPerformed(evt);
            }
        });

        clerk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        clerk.setText("I'm a clerk");
        clerk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkActionPerformed(evt);
            }
        });

        worksEngineer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        worksEngineer.setText("I'm a works engineer");
        worksEngineer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worksEngineerActionPerformed(evt);
            }
        });

        showAll.setText("Show all rental requests");
        showAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tekstbuildit)
                        .addContainerGap(426, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(worksEngineer)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(siteEngineer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                .addComponent(clerk, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(showAll, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(showAll)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tekstbuildit)
                                .addGap(32, 32, 32)
                                .addComponent(siteEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107))
                            .addComponent(clerk, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addComponent(worksEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void siteEngineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siteEngineerActionPerformed
        this.setVisible(false);
        StartschermSiteEngineer SE;
               //try {
                   SE = new StartschermSiteEngineer(); 
                   SE.setVisible(true);
               //} 
               /*catch (DBException ex) {
                   Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
               }
               */
    }//GEN-LAST:event_siteEngineerActionPerformed

    private void clerkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkActionPerformed
        this.setVisible(false);
        StartschermClerk SE;
               //try {
                   SE = new StartschermClerk(); 
                   SE.setVisible(true);
               //} 
               /*catch (DBException ex) {
                   Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
               }
               */
    }//GEN-LAST:event_clerkActionPerformed

    private void worksEngineerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worksEngineerActionPerformed
        this.setVisible(false);
        StartschermWorkEngineer WO;
               //try {
                   WO = new StartschermWorkEngineer(); 
                   WO.setVisible(true);
               //} 
               /*catch (DBException ex) {
                   Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
               }
               */
    }//GEN-LAST:event_worksEngineerActionPerformed

    private void showAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showAllActionPerformed
        // TOON EEN LIJST MET ALLE AANGEMAAKTE RR'S
        this.setVisible(false);
        StartSchermShowRentalRequests show;
        try {
            show = new StartSchermShowRentalRequests();
            show.setVisible(true);
        } catch (DBException ex) {
            System.out.println("Error bij StartSchermShowRentalRequests");
        }
        
        //StartSchermShowRentalRequests.getStartschermShow().setVisible(true);
    }//GEN-LAST:event_showAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startscherm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startscherm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clerk;
    private javax.swing.JButton showAll;
    private javax.swing.JButton siteEngineer;
    private javax.swing.JLabel tekstbuildit;
    private javax.swing.JButton worksEngineer;
    // End of variables declaration//GEN-END:variables
}
